# Generated by Django 5.1 on 2024-08-14 00:57

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries ={
        "published":"Apost avalibale for all to view",
        "draft":"A post only visible tot he author",
        "archived":"An older post, visible to logged in users"
    }
    Status = apps.get_model("posts", "status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
